#!/bin/bash

yad --notification --image=/home/$USER/icons/jiggles.png --text "jiggle jiggle"  &
pid=$!


while kill -0 $pid 2> /dev/null; do
     xdotool mousemove_relative -- `seq -10 10 | shuf -n 1` `seq -10 10 | shuf -n 1`
     sleep 60
done
